name: Bump version

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    environment:
      name: pypi
      url: https://pypi.org/p/bencherscaffold
    permissions:
      id-token: write
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Poetry
        uses: snok/install-poetry@v1

      - name: Install project
        run: poetry install --with dev --no-root

      - name: Bump version and commit
        # if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags')
        run: |
          poetry run python bump_version.py
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git commit -am "Bump version"
          git push

      - name: Build
        #if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags')
        run: poetry build

      - name: Publish package distributions to PyPI
        #if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags')
        uses: pypa/gh-action-pypi-publish@release/v1

      - name: Run update scaffold action in bencher repo
        #if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags')
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.BENCHER_TOKEN }}
          script: |
            await github.rest.actions.createWorkflowDispatch({
              owner: 'lpapenme',
              repo: 'bencher',
              ref: 'main',
              workflow_id: 'update_scaffold_version.yml'
            });


